const studios = [
  'Music Boutique',
  'Music Crew',
  'Unique Music',
  'Vanomic',
  'Funky Hearts',
  'Spunky Beans',
  'Bored Brothers',
  'Lucent House',
  'Spectral Dreams',
  'Lumasonic',
  'Tellular',
  'Virtuaris',
  'Onetimee',
  'Dash Genius',
  'Activity Bag',
  'Pheale',
  'Saxene',
  'MixPods',
  'Superb Story',
  'Click Concert',
  'Dexonic',
  'Orgasmist',
  'Crimson Royale',
  'Freelyng',
  'Bumbaloo',
  'Stomp Around',
  'MrktKng',
  'Hardcore Hero',
  'StreamZing',
  'SmashVibe',
  'MentalMist',
  'Play Fairy',
  'PopStax',
  'DABMO',
  'SYNZU',
  'City Mingles',
  'UberPlayer',
  'Sound Bowl',
  'HipTUBE',
  'Altarcade',
  'Sunset Gem',
  'RapBack',
  'Gecko Country',
  'Seratina',
  'Leisure Fox',
  'OPEN SHOW',
  'Nukito',
  'Night Sugar',
  'Magictutor',
  'PALADIR',
  'Bodoko',
  'Disco Monster',
  'Factory Merch',
  'Trinola',
  'MonkeyUncle',
  'PINKTWIGS',
  'Zadoa',
  'BuffalloSaloon',
  'Edittime',
  'Legal Devil',
  'TenPipes',
  'Sound Instinct',
  'Pay 4 Performance',
  'Voicewave',
  'Rap Saavy',
  'Rival Icon',
  'KIP PROPHET',
  'FunkyDrum',
  'Storm Fever',
  'Soundeca',
  'First Rehearsal',
  'Valiant City',
  'Sonic Mantra',
  'Podtrax',
  'Attuna',
  'VOLOXY',
  'Kyopi',
  'EverGenie',
  'SonicSwan',
  'AtomBoom',
  'Vivaphonic',
  'MEGASHRED',
  'Ampeur',
  'Cocktail Circuit',
  'Cymbalis',
  'Grunge Logic',
  'Onyx Angel',
  'Third Wish',
  'Afternoon News',
  'Jackpot Saloon',
  'GoofyGoose',
  'Shookk',
  'Story Fellas',
  'IvyTap',
  'Rebellogic',
  'Sonabar',
  'Sirensa',
  'HawtDogz',
  'Vobz',
  'Rumble Crew'
];

const bands = [
  'Down Home Agita',
  'Amperstellar',
  'Azure Nation',
  'Tonephile',
  'Catastrophe',
  'Chronic Caterwaulers',
  'The Alligator Miseries',
  'Eggcorn',
  'Highfalutin',
  'Lushpuppy',
  'Nine Percent Pockets',
  'Lackamusical',
  'Majordemo',
  'Bass Menagerie',
  'Mnemonic Miasma',
  'Murmuration',
  'Onomatopie',
  'PseudoSounds',
  'Slapdash',
  'Martini California',
  'Staccato',
  'Toothsome',
  'Uproar To Ghost 128',
  'Boss Beesleep Ave',
  'The Dreamer Showgirls',
  'Swallow Tail Galactic',
  'Pedal 405',
  'Bop Rainbows',
  'Purple Harmony',
  'Sleep January',
  'Cookie Demagogue',
  'Doom Bachelor',
  'The Head Around',
  'Onslaught Motel',
  'Below Ground',
  'Devil Path',
  'Tadpole',
  'The River to Malta',
  'Toxic Thrust',
  'Grave Sonic',
  'The Texas Between Radios',
  'The Hang Ten Metals',
  'Fiddle Over Saddle',
  'Lucky Hammers',
  'The Lineup',
  'Beyond Hurricanes',
  'The Dixie Cacophony',
  'Mother Williams Bang',
  'Satan Skirmish',
  'The Desert Lady Shuffle',
  'Coconut 81',
  'California Harleys',
  'Flame Jimmy Din',
  'Air Above Commotion',
  'Trauma Turbulence',
  'Tropical Cops',
  'Do Clang',
  'The Roadside Blinks',
  'Revolting Crocodiles',
  'Diner Pioneers',
  'The Impact Noises',
  'The Aggression',
  'Baby Blade',
  'The Tonality Cats',
  'Clatter Around Aires',
  'Bloody Fin',
  'Pandemonium Below',
  'The Settler Snap Cannons',
  'Evil Stingray',
  'Velvet Ambush',
  'Mustang Wednesday',
  'Bikini Foot',
  'Highway Onslaught',
  'Continental Yelp',
  'The Jangles',
  'Zombie Drive-Thru',
  'Ghost Fuss',
  'Dice Outbreak 53',
  'Lament Lounge',
  'Claw Snake',
  'The Mighty Blitzes',
  'Roller Mandolin',
  'Honeybee Elephants',
  'Shouting Discord',
  'Urban Malcontent',
  'Zebra Punch',
  'One-Eyed Roulette',
  'Hot Chorus',
  'Hoo-Ha 77',
  'Violent Ray',
  'Chainmail Spiders',
  'The Light Beyond Opal Valley',
  'Gumdrop Spaceship',
  'Lucid Apostate',
  'The Watusi Encroachment',
  'Secret Progeny',
  'After The Missles',
  'Finger Brawl',
  'The Fearsome Onrush',
  'Butterfly Blvd.'
];

let makeEntry = (id) => {
  let band = bands[Math.floor(Math.random() * 100)];
  let studio = studios[Math.floor(Math.random() * 100)];
  let newEntry = {
    songId: id,
    bandId: id,
    bandName: band,
    description: `Recorded, mixed, and mastered at ${studio} Studios. Produced by ${band}. © 2021 ${band}. All rights reserved.`
  };
  return newEntry;
};

module.exports.makeEntry = makeEntry;